// Emoji stickers for meme creation
// Each sticker has an emoji character that renders as text on canvas

export const STICKERS = [
  { id: 'rocket', name: 'Rocket', emoji: '🚀' },
  { id: 'fire', name: 'Fire', emoji: '🔥' },
  { id: 'money', name: 'Money', emoji: '💰' },
  { id: 'diamond', name: 'Diamond', emoji: '💎' },
  { id: 'skull', name: 'Skull', emoji: '💀' },
  { id: 'clown', name: 'Clown', emoji: '🤡' },
  { id: 'crying-laughing', name: 'Crying Laughing', emoji: '😂' },
  { id: 'eyes', name: 'Eyes', emoji: '👀' },
  { id: 'moon', name: 'Moon', emoji: '🌙' },
  { id: 'crown', name: 'Crown', emoji: '👑' },
  { id: 'poop', name: 'Poop', emoji: '💩' },
  { id: 'chart-up', name: 'Chart Up', emoji: '📈' },
  { id: 'chart-down', name: 'Chart Down', emoji: '📉' },
  { id: 'money-wings', name: 'Money Wings', emoji: '💸' },
  { id: 'brain', name: 'Brain', emoji: '🧠' },
  { id: 'gorilla', name: 'Ape', emoji: '🦍' },
  { id: 'bear', name: 'Bear', emoji: '🐻' },
  { id: 'bull', name: 'Bull', emoji: '🐂' },
  { id: 'whale', name: 'Whale', emoji: '🐋' },
  { id: 'frog', name: 'Frog', emoji: '🐸' },
  { id: 'dog', name: 'Dog', emoji: '🐕' },
  { id: 'cat', name: 'Cat', emoji: '🐈' },
  { id: 'goat', name: 'GOAT', emoji: '🐐' },
  { id: 'explosion', name: 'Explosion', emoji: '💥' },
  { id: 'star', name: 'Star', emoji: '⭐' },
  { id: 'gem', name: 'Gem', emoji: '💎' },
  { id: 'target', name: 'Target', emoji: '🎯' },
  { id: 'trophy', name: 'Trophy', emoji: '🏆' },
  { id: 'alarm', name: 'Alarm', emoji: '🚨' },
  { id: 'warning', name: 'Warning', emoji: '⚠️' },
  { id: 'check', name: 'Check', emoji: '✅' },
  { id: 'x', name: 'X', emoji: '❌' },
  { id: 'hundred', name: '100', emoji: '💯' },
  { id: 'thumbs-up', name: 'Thumbs Up', emoji: '👍' },
  { id: 'thumbs-down', name: 'Thumbs Down', emoji: '👎' },
  { id: 'middle-finger', name: 'Middle Finger', emoji: '🖕' },
  { id: 'pray', name: 'Pray', emoji: '🙏' },
  { id: 'muscle', name: 'Muscle', emoji: '💪' },
  { id: 'handshake', name: 'Handshake', emoji: '🤝' },
  { id: 'point-right', name: 'Point Right', emoji: '👉' },
  { id: 'point-left', name: 'Point Left', emoji: '👈' },
  { id: 'sunglasses', name: 'Sunglasses', emoji: '😎' },
  { id: 'nerd', name: 'Nerd', emoji: '🤓' },
  { id: 'angry', name: 'Angry', emoji: '😤' },
  { id: 'thinking', name: 'Thinking', emoji: '🤔' },
  { id: 'shock', name: 'Shock', emoji: '😱' },
  { id: 'cap', name: 'Cap', emoji: '🧢' },
  { id: 'no-cap', name: 'No Cap', emoji: '🚫🧢' },
]

export default STICKERS
